'''OpenGL extension EXT.device_query

This module customises the behaviour of the 
OpenGL.raw.EGL.EXT.device_query to provide a more 
Python-friendly API

The official definition of this extension is available here:
http://www.opengl.org/registry/specs/EXT/device_query.txt
'''
from OpenGL import platform, constant, arrays
from OpenGL import extensions, wrapper
import ctypes
from OpenGL.raw.EGL import _types, _glgets
from OpenGL.raw.EGL.EXT.device_query import *
from OpenGL.raw.EGL.EXT.device_query import _EXTENSION_NAME

def glInitDeviceQueryEXT():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( _EXTENSION_NAME )


### END AUTOGENERATED SECTION

eglQueryDeviceStringEXT.extension = None
eglQueryDeviceStringEXT.force_extension = True 
