'''Autogenerated by xml_generate script, do not edit!'''
from OpenGL import platform as _p, arrays
# Code generation uses this
from OpenGL.raw.GL import _types as _cs
# End users want this...
from OpenGL.raw.GL._types import *
from OpenGL.raw.GL import _errors
from OpenGL.constant import Constant as _C

import ctypes
_EXTENSION_NAME = 'GL_EXT_stencil_clear_tag'
def _f( function ):
    return _p.createFunction( function,_p.PLATFORM.GL,'GL_EXT_stencil_clear_tag',error_checker=_errors._error_checker)
GL_STENCIL_CLEAR_TAG_VALUE_EXT=_C('GL_STENCIL_CLEAR_TAG_VALUE_EXT',0x88F3)
GL_STENCIL_TAG_BITS_EXT=_C('GL_STENCIL_TAG_BITS_EXT',0x88F2)
@_f
@_p.types(None,_cs.GLsizei,_cs.GLuint)
def glStencilClearTagEXT(stencilTagBits,stencilClearTag):pass
