'''Autogenerated by xml_generate script, do not edit!'''
from OpenGL import platform as _p, arrays
# Code generation uses this
from OpenGL.raw.GL import _types as _cs
# End users want this...
from OpenGL.raw.GL._types import *
from OpenGL.raw.GL import _errors
from OpenGL.constant import Constant as _C

import ctypes
_EXTENSION_NAME = 'GL_APPLE_texture_range'
def _f( function ):
    return _p.createFunction( function,_p.PLATFORM.GL,'GL_APPLE_texture_range',error_checker=_errors._error_checker)
GL_STORAGE_CACHED_APPLE=_C('GL_STORAGE_CACHED_APPLE',0x85BE)
GL_STORAGE_PRIVATE_APPLE=_C('GL_STORAGE_PRIVATE_APPLE',0x85BD)
GL_STORAGE_SHARED_APPLE=_C('GL_STORAGE_SHARED_APPLE',0x85BF)
GL_TEXTURE_RANGE_LENGTH_APPLE=_C('GL_TEXTURE_RANGE_LENGTH_APPLE',0x85B7)
GL_TEXTURE_RANGE_POINTER_APPLE=_C('GL_TEXTURE_RANGE_POINTER_APPLE',0x85B8)
GL_TEXTURE_STORAGE_HINT_APPLE=_C('GL_TEXTURE_STORAGE_HINT_APPLE',0x85BC)
@_f
@_p.types(None,_cs.GLenum,_cs.GLenum,arrays.GLvoidpArray)
def glGetTexParameterPointervAPPLE(target,pname,params):pass
@_f
@_p.types(None,_cs.GLenum,_cs.GLsizei,ctypes.c_void_p)
def glTextureRangeAPPLE(target,length,pointer):pass
