'''Autogenerated by xml_generate script, do not edit!'''
from OpenGL import platform as _p, arrays
# Code generation uses this
from OpenGL.raw.GLX import _types as _cs
# End users want this...
from OpenGL.raw.GLX._types import *
from OpenGL.raw.GLX import _errors
from OpenGL.constant import Constant as _C

import ctypes
_EXTENSION_NAME = 'GLX_EXT_stereo_tree'
def _f( function ):
    return _p.createFunction( function,_p.PLATFORM.GLX,'GLX_EXT_stereo_tree',error_checker=_errors._error_checker)
GLX_STEREO_NOTIFY_EXT=_C('GLX_STEREO_NOTIFY_EXT',0x00000000)
GLX_STEREO_NOTIFY_MASK_EXT=_C('GLX_STEREO_NOTIFY_MASK_EXT',0x00000001)
GLX_STEREO_TREE_EXT=_C('GLX_STEREO_TREE_EXT',0x20F5)

