#!/usr/bin/python2.7
# -*- coding: utf-8 -*-

"""
**Project Name:**      MakeHuman

**Product Home Page:** http://www.makehuman.org/

**Code Home Page:**    https://bitbucket.org/MakeHuman/makehuman/

**Authors:**           Manuel Bastioni, Thomas Larsson

**Copyright(c):**      MakeHuman Team 2001-2014

**Licensing:**         AGPL3 (http://www.makehuman.org/doc/node/the_makehuman_application.html)

    This file is part of MakeHuman (www.makehuman.org).

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

**Coding Standards:**  See http://www.makehuman.org/node/165

Abstract
--------

The official MakeHuman rig
"""

from .flags import *


Joints = [
  ('root_tl', 'j', 'pelvis'),
  ('pelvis.R_tl', 'j', 'r-upper-leg'),
  ('upperleg.R_tl', 'j', 'r-knee'),
  ('lowerleg02.R_tl', 'j', 'r-ankle'),
  ('metatarsal1.R_tl', 'j', 'r-toe-1-1'),
  ('toe1-1.R_tl', 'j', 'r-toe-1-2'),
  ('toe1-2.R_tl', 'j', 'r-toe-1-3'),
  ('metatarsal4.R_tl', 'j', 'r-toe-4-1'),
  ('toe4-1.R_tl', 'j', 'r-toe-4-2'),
  ('toe4-2.R_tl', 'j', 'r-toe-4-3'),
  ('toe4-3.R_tl', 'j', 'r-toe-4-4'),
  ('metatarsal3.R_tl', 'j', 'r-toe-3-1'),
  ('toe3-1.R_tl', 'j', 'r-toe-3-2'),
  ('toe3-2.R_tl', 'j', 'r-toe-3-3'),
  ('toe3-3.R_tl', 'j', 'r-toe-3-4'),
  ('metatarsal5.R_tl', 'j', 'r-toe-5-1'),
  ('toe5-1.R_tl', 'j', 'r-toe-5-2'),
  ('toe5-2.R_tl', 'j', 'r-toe-5-3'),
  ('toe5-3.R_tl', 'j', 'r-toe-5-4'),
  ('heel.R_tl', 'v', 5845),
  ('metatarsal2.R_tl', 'j', 'r-toe-2-1'),
  ('toe2-1.R_tl', 'j', 'r-toe-2-2'),
  ('toe2-2.R_tl', 'j', 'r-toe-2-3'),
  ('toe2-3.R_tl', 'j', 'r-toe-2-4'),
  ('pelvis.L_tl', 'j', 'l-upper-leg'),
  ('upperleg.L_tl', 'j', 'l-knee'),
  ('lowerleg02.L_tl', 'j', 'l-ankle'),
  ('metatarsal1.L_tl', 'j', 'l-toe-1-1'),
  ('toe1-1.L_tl', 'j', 'l-toe-1-2'),
  ('toe1-2.L_tl', 'j', 'l-toe-1-3'),
  ('metatarsal5.L_tl', 'j', 'l-toe-5-1'),
  ('toe5-1.L_tl', 'j', 'l-toe-5-2'),
  ('toe5-2.L_tl', 'j', 'l-toe-5-3'),
  ('toe5-3.L_tl', 'j', 'l-toe-5-4'),
  ('metatarsal3.L_tl', 'j', 'l-toe-3-1'),
  ('toe3-1.L_tl', 'j', 'l-toe-3-2'),
  ('toe3-2.L_tl', 'j', 'l-toe-3-3'),
  ('toe3-3.L_tl', 'j', 'l-toe-3-4'),
  ('metatarsal2.L_tl', 'j', 'l-toe-2-1'),
  ('toe2-1.L_tl', 'j', 'l-toe-2-2'),
  ('toe2-2.L_tl', 'j', 'l-toe-2-3'),
  ('toe2-3.L_tl', 'j', 'l-toe-2-4'),
  ('heel.L_tl', 'v', 12442),
  ('metatarsal4.L_tl', 'j', 'l-toe-4-1'),
  ('toe4-1.L_tl', 'j', 'l-toe-4-2'),
  ('toe4-2.L_tl', 'j', 'l-toe-4-3'),
  ('toe4-3.L_tl', 'j', 'l-toe-4-4'),
  ('spine5_tl', 'j', 'spine-4'),
  ('spine4_tl', 'j', 'spine-3'),
  ('spine3_tl', 'j', 'spine-2'),
  ('spine2_tl', 'j', 'spine-1'),
  ('spine1_tl', 'j', 'neck'),
  ('clavicle.L_hd', 'v', 8161),
  ('clavicle.L_tl', 'v', 8077),
  ('shoulder.L_tl', 'j', 'l-shoulder'),
  ('scapula.L_hd', 'v', 8230),
  ('scapula.L_tl', 'v', 8252),
  ('upperarm01.L_hd', 'j', 'l-shoulder'),
  ('upperarm02.L_tl', 'j', 'l-elbow'),
  ('lowerarm02.L_tl', 'j', 'l-hand'),
  ('wrist.L_tl', 'j', 'l-hand-3'),
  ('finger1-1.L_hd', 'j', 'l-finger-1-1'),
  ('finger1-1.L_tl', 'j', 'l-finger-1-2'),
  ('finger1-2.L_tl', 'j', 'l-finger-1-3'),
  ('finger1-3.L_tl', 'j', 'l-finger-1-4'),
  ('metacarpal4.L_hd', 'j', 'l-hand-2'),
  ('metacarpal4.L_tl', 'j', 'l-finger-5-1'),
  ('finger5-1.L_tl', 'j', 'l-finger-5-2'),
  ('finger5-2.L_tl', 'j', 'l-finger-5-3'),
  ('finger5-3.L_tl', 'j', 'l-finger-5-4'),
  ('metacarpal1.L_tl', 'j', 'l-finger-2-1'),
  ('finger2-1.L_tl', 'j', 'l-finger-2-2'),
  ('finger2-2.L_tl', 'j', 'l-finger-2-3'),
  ('finger2-3.L_tl', 'j', 'l-finger-2-4'),
  ('metacarpal2.L_tl', 'j', 'l-finger-3-1'),
  ('finger3-1.L_tl', 'j', 'l-finger-3-2'),
  ('finger3-2.L_tl', 'j', 'l-finger-3-3'),
  ('finger3-3.L_tl', 'j', 'l-finger-3-4'),
  ('metacarpal3.L_hd', 'j', 'l-hand-2'),
  ('metacarpal3.L_tl', 'j', 'l-finger-4-1'),
  ('finger4-1.L_tl', 'j', 'l-finger-4-2'),
  ('finger4-2.L_tl', 'j', 'l-finger-4-3'),
  ('finger4-3.L_tl', 'j', 'l-finger-4-4'),
  ('clavicle.R_hd', 'v', 1475),
  ('clavicle.R_tl', 'v', 1385),
  ('upperarm01.R_hd', 'j', 'r-shoulder'),
  ('upperarm02.R_tl', 'j', 'r-elbow'),
  ('lowerarm02.R_tl', 'j', 'r-hand'),
  ('wrist.R_tl', 'j', 'r-hand-3'),
  ('finger1-1.R_hd', 'j', 'r-finger-1-1'),
  ('finger1-1.R_tl', 'j', 'r-finger-1-2'),
  ('finger1-2.R_tl', 'j', 'r-finger-1-3'),
  ('finger1-3.R_tl', 'j', 'r-finger-1-4'),
  ('metacarpal4.R_hd', 'j', 'r-hand-2'),
  ('metacarpal4.R_tl', 'j', 'r-finger-5-1'),
  ('finger5-1.R_tl', 'j', 'r-finger-5-2'),
  ('finger5-2.R_tl', 'j', 'r-finger-5-3'),
  ('finger5-3.R_tl', 'j', 'r-finger-5-4'),
  ('metacarpal1.R_tl', 'j', 'r-finger-2-1'),
  ('finger2-1.R_tl', 'j', 'r-finger-2-2'),
  ('finger2-2.R_tl', 'j', 'r-finger-2-3'),
  ('finger2-3.R_tl', 'j', 'r-finger-2-4'),
  ('metacarpal2.R_tl', 'j', 'r-finger-3-1'),
  ('finger3-1.R_tl', 'j', 'r-finger-3-2'),
  ('finger3-2.R_tl', 'j', 'r-finger-3-3'),
  ('finger3-3.R_tl', 'j', 'r-finger-3-4'),
  ('metacarpal3.R_hd', 'j', 'r-hand-2'),
  ('metacarpal3.R_tl', 'j', 'r-finger-4-1'),
  ('finger4-1.R_tl', 'j', 'r-finger-4-2'),
  ('finger4-2.R_tl', 'j', 'r-finger-4-3'),
  ('finger4-3.R_tl', 'j', 'r-finger-4-4'),
  ('shoulder.R_tl', 'j', 'r-shoulder'),
  ('scapula.R_hd', 'v', 1552),
  ('scapula.R_tl', 'v', 1574),
  ('neck_tl', 'j', 'head'),
  ('platysma06.R_hd', 'v', 777),
  ('platysma06.R_tl', 'v', 1035),
  ('platysma06.L_hd', 'v', 7496),
  ('platysma06.L_tl', 'v', 7727),
  ('head_tl', 'j', 'head-2'),
  ('jaw_hd', 'j', 'mouth'),
  ('jaw_tl', 'v', 991),
  ('tongue00_tl', 'j', 'tongue-1'),
  ('tongue01_tl', 'j', 'tongue-2'),
  ('tongue02_tl', 'j', 'tongue-3'),
  ('tongue04_tl', 'j', 'tongue-4'),
  ('eye.R_hd', 'j', 'r-eye'),
  ('eye.R_tl', 'j', 'r-eye-target'),
  ('eye.L_hd', 'j', 'l-eye'),
  ('eye.L_tl', 'j', 'l-eye-target'),
  ('orbicularis04.R_hd', 'j', 'r-eye'),
  ('orbicularis04.R_tl', 'j', 'r-lowerlid'),
  ('orbicularis04.L_hd', 'j', 'l-eye'),
  ('orbicularis04.L_tl', 'j', 'l-lowerlid'),
  ('levator02.R_hd', 'v', 5062),
  ('levator02.R_tl', 'v', 184),
  ('levator03.R_tl', 'v', 5321),
  ('levator04.R_tl', 'v', 3739),
  ('levator05.R_tl', 'v', 399),
  ('temporalis02.L_hd', 'v', 11797),
  ('temporalis02.L_tl', 'v', 11704),
  ('temporalis03.L_tl', 'v', 6968),
  ('risorius02.L_tl', 'v', 11927),
  ('risorius03.L_tl', 'v', 11819),
  ('levator02.L_hd', 'v', 11679),
  ('levator02.L_tl', 'v', 6960),
  ('levator03.L_tl', 'v', 11925),
  ('levator04.L_tl', 'v', 10407),
  ('levator05.L_tl', 'v', 7159),
  ('special01_hd', 'v', 5266),
  ('special01_tl', 'v', 343),
  ('oris04.R_tl', 'v', 5073),
  ('oris03.R_tl', 'v', 410),
  ('oris04.L_tl', 'v', 11688),
  ('oris03.L_tl', 'v', 7170),
  ('oris05_tl', 'v', 362),
  ('special02_hd', 'j', 'mouth'),
  ('special02_tl', 'v', 5162),
  ('oris06.L_tl', 'v', 7450),
  ('oris07.L_tl', 'v', 7166),
  ('oris06.R_tl', 'v', 728),
  ('oris07.R_tl', 'v', 406),
  ('oris02_hd', 'v', 5162),
  ('oris02_tl', 'v', 491),
  ('oris01_tl', 'v', 494),
  ('temporalis01.L_hd', 'v', 10409),
  ('temporalis01.L_tl', 'v', 6986),
  ('oculi02.L_tl', 'v', 6996),
  ('oculi01.L_tl', 'v', 7006),
  ('oculi03.L_tl', 'v', 6995),
  ('temporalis01.R_hd', 'v', 3741),
  ('temporalis01.R_tl', 'v', 211),
  ('oculi02.R_tl', 'v', 222),
  ('oculi01.R_tl', 'v', 233),
  ('oculi03.R_tl', 'v', 221),
  ('temporalis02.R_hd', 'v', 5185),
  ('temporalis02.R_tl', 'v', 5089),
  ('temporalis03.R_tl', 'v', 192),
  ('risorius02.R_tl', 'v', 5323),
  ('risorius03.R_tl', 'v', 5208),
  ('orbicularis03.R_hd', 'j', 'r-eye'),
  ('orbicularis03.R_tl', 'j', 'r-upperlid'),
  ('orbicularis03.L_hd', 'j', 'l-eye'),
  ('orbicularis03.L_tl', 'j', 'l-upperlid'),
  ('frontalis02.L_hd', 'v', 7443),
  ('frontalis02.L_tl', 'v', 7437),
  ('frontalis01.L_tl', 'v', 7015),
  ('frontalis02.R_hd', 'v', 720),
  ('frontalis02.R_tl', 'v', 714),
  ('frontalis01.R_tl', 'v', 245),
  ('special03_hd', 'j', 'mouth'),
  ('special03_tl', 'v', 5134),
  ('levator06.R_hd', 'v', 295),
  ('levator06.R_tl', 'v', 5069),
  ('levator06.L_hd', 'v', 7062),
  ('levator06.L_tl', 'v', 11685),
  ('platysma03.R_hd', 'v', 808),
  ('platysma03.R_tl', 'v', 1038),
  ('platysma03.L_hd', 'v', 7521),
  ('platysma03.L_tl', 'v', 7730),
  ('lowerleg01.R_tl', 'l', ((0.5000, 'upperleg.R_tl'), (0.5000, 'lowerleg02.R_tl'))),
  ('lowerleg01.L_tl', 'l', ((0.5000, 'upperleg.L_tl'), (0.5000, 'lowerleg02.L_tl'))),
  ('upperarm01.L_tl', 'l', ((0.7115, 'upperarm01.L_hd'), (0.2885, 'upperarm02.L_tl'))),
  ('lowerarm01.L_tl', 'l', ((0.4981, 'upperarm02.L_tl'), (0.5019, 'lowerarm02.L_tl'))),
  ('upperarm01.R_tl', 'l', ((0.7115, 'upperarm01.R_hd'), (0.2885, 'upperarm02.R_tl'))),
  ('lowerarm01.R_tl', 'l', ((0.4981, 'upperarm02.R_tl'), (0.5019, 'lowerarm02.R_tl'))),
  ('tongue03_tl', 'l', ((0.5000, 'tongue02_tl'), (0.5000, 'tongue04_tl'))),

]

HeadsTails = {
  'root' : (('root_tl', (0,0,-1)), 'root_tl'),
  'pelvis.R' : ('root_tl', 'pelvis.R_tl'),
  'upperleg.R' : ('pelvis.R_tl', 'upperleg.R_tl'),
  'lowerleg01.R' : ('upperleg.R_tl', 'lowerleg01.R_tl'),
  'lowerleg02.R' : ('lowerleg01.R_tl', 'lowerleg02.R_tl'),
  'metatarsal1.R' : ('lowerleg02.R_tl', 'metatarsal1.R_tl'),
  'toe1-1.R' : ('metatarsal1.R_tl', 'toe1-1.R_tl'),
  'toe1-2.R' : ('toe1-1.R_tl', 'toe1-2.R_tl'),
  'metatarsal4.R' : ('lowerleg02.R_tl', 'metatarsal4.R_tl'),
  'toe4-1.R' : ('metatarsal4.R_tl', 'toe4-1.R_tl'),
  'toe4-2.R' : ('toe4-1.R_tl', 'toe4-2.R_tl'),
  'toe4-3.R' : ('toe4-2.R_tl', 'toe4-3.R_tl'),
  'metatarsal3.R' : ('lowerleg02.R_tl', 'metatarsal3.R_tl'),
  'toe3-1.R' : ('metatarsal3.R_tl', 'toe3-1.R_tl'),
  'toe3-2.R' : ('toe3-1.R_tl', 'toe3-2.R_tl'),
  'toe3-3.R' : ('toe3-2.R_tl', 'toe3-3.R_tl'),
  'metatarsal5.R' : ('lowerleg02.R_tl', 'metatarsal5.R_tl'),
  'toe5-1.R' : ('metatarsal5.R_tl', 'toe5-1.R_tl'),
  'toe5-2.R' : ('toe5-1.R_tl', 'toe5-2.R_tl'),
  'toe5-3.R' : ('toe5-2.R_tl', 'toe5-3.R_tl'),
  'heel.R' : ('lowerleg02.R_tl', 'heel.R_tl'),
  'metatarsal2.R' : ('lowerleg02.R_tl', 'metatarsal2.R_tl'),
  'toe2-1.R' : ('metatarsal2.R_tl', 'toe2-1.R_tl'),
  'toe2-2.R' : ('toe2-1.R_tl', 'toe2-2.R_tl'),
  'toe2-3.R' : ('toe2-2.R_tl', 'toe2-3.R_tl'),
  'pelvis.L' : ('root_tl', 'pelvis.L_tl'),
  'upperleg.L' : ('pelvis.L_tl', 'upperleg.L_tl'),
  'lowerleg01.L' : ('upperleg.L_tl', 'lowerleg01.L_tl'),
  'lowerleg02.L' : ('lowerleg01.L_tl', 'lowerleg02.L_tl'),
  'metatarsal1.L' : ('lowerleg02.L_tl', 'metatarsal1.L_tl'),
  'toe1-1.L' : ('metatarsal1.L_tl', 'toe1-1.L_tl'),
  'toe1-2.L' : ('toe1-1.L_tl', 'toe1-2.L_tl'),
  'metatarsal5.L' : ('lowerleg02.L_tl', 'metatarsal5.L_tl'),
  'toe5-1.L' : ('metatarsal5.L_tl', 'toe5-1.L_tl'),
  'toe5-2.L' : ('toe5-1.L_tl', 'toe5-2.L_tl'),
  'toe5-3.L' : ('toe5-2.L_tl', 'toe5-3.L_tl'),
  'metatarsal3.L' : ('lowerleg02.L_tl', 'metatarsal3.L_tl'),
  'toe3-1.L' : ('metatarsal3.L_tl', 'toe3-1.L_tl'),
  'toe3-2.L' : ('toe3-1.L_tl', 'toe3-2.L_tl'),
  'toe3-3.L' : ('toe3-2.L_tl', 'toe3-3.L_tl'),
  'metatarsal2.L' : ('lowerleg02.L_tl', 'metatarsal2.L_tl'),
  'toe2-1.L' : ('metatarsal2.L_tl', 'toe2-1.L_tl'),
  'toe2-2.L' : ('toe2-1.L_tl', 'toe2-2.L_tl'),
  'toe2-3.L' : ('toe2-2.L_tl', 'toe2-3.L_tl'),
  'heel.L' : ('lowerleg02.L_tl', 'heel.L_tl'),
  'metatarsal4.L' : ('lowerleg02.L_tl', 'metatarsal4.L_tl'),
  'toe4-1.L' : ('metatarsal4.L_tl', 'toe4-1.L_tl'),
  'toe4-2.L' : ('toe4-1.L_tl', 'toe4-2.L_tl'),
  'toe4-3.L' : ('toe4-2.L_tl', 'toe4-3.L_tl'),
  'spine5' : ('root_tl', 'spine5_tl'),
  'spine4' : ('spine5_tl', 'spine4_tl'),
  'spine3' : ('spine4_tl', 'spine3_tl'),
  'spine2' : ('spine3_tl', 'spine2_tl'),
  'spine1' : ('spine2_tl', 'spine1_tl'),
  'clavicle.L' : ('clavicle.L_hd', 'clavicle.L_tl'),
  'shoulder.L' : ('clavicle.L_tl', 'shoulder.L_tl'),
  'scapula.L' : ('scapula.L_hd', 'scapula.L_tl'),
  'upperarm01.L' : ('upperarm01.L_hd', 'upperarm01.L_tl'),
  'upperarm02.L' : ('upperarm01.L_tl', 'upperarm02.L_tl'),
  'lowerarm01.L' : ('upperarm02.L_tl', 'lowerarm01.L_tl'),
  'lowerarm02.L' : ('lowerarm01.L_tl', 'lowerarm02.L_tl'),
  'wrist.L' : ('lowerarm02.L_tl', 'wrist.L_tl'),
  'finger1-1.L' : ('finger1-1.L_hd', 'finger1-1.L_tl'),
  'finger1-2.L' : ('finger1-1.L_tl', 'finger1-2.L_tl'),
  'finger1-3.L' : ('finger1-2.L_tl', 'finger1-3.L_tl'),
  'metacarpal4.L' : ('metacarpal4.L_hd', 'metacarpal4.L_tl'),
  'finger5-1.L' : ('metacarpal4.L_tl', 'finger5-1.L_tl'),
  'finger5-2.L' : ('finger5-1.L_tl', 'finger5-2.L_tl'),
  'finger5-3.L' : ('finger5-2.L_tl', 'finger5-3.L_tl'),
  'metacarpal1.L' : ('wrist.L_tl', 'metacarpal1.L_tl'),
  'finger2-1.L' : ('metacarpal1.L_tl', 'finger2-1.L_tl'),
  'finger2-2.L' : ('finger2-1.L_tl', 'finger2-2.L_tl'),
  'finger2-3.L' : ('finger2-2.L_tl', 'finger2-3.L_tl'),
  'metacarpal2.L' : ('wrist.L_tl', 'metacarpal2.L_tl'),
  'finger3-1.L' : ('metacarpal2.L_tl', 'finger3-1.L_tl'),
  'finger3-2.L' : ('finger3-1.L_tl', 'finger3-2.L_tl'),
  'finger3-3.L' : ('finger3-2.L_tl', 'finger3-3.L_tl'),
  'metacarpal3.L' : ('metacarpal3.L_hd', 'metacarpal3.L_tl'),
  'finger4-1.L' : ('metacarpal3.L_tl', 'finger4-1.L_tl'),
  'finger4-2.L' : ('finger4-1.L_tl', 'finger4-2.L_tl'),
  'finger4-3.L' : ('finger4-2.L_tl', 'finger4-3.L_tl'),
  'clavicle.R' : ('clavicle.R_hd', 'clavicle.R_tl'),
  'upperarm01.R' : ('upperarm01.R_hd', 'upperarm01.R_tl'),
  'upperarm02.R' : ('upperarm01.R_tl', 'upperarm02.R_tl'),
  'lowerarm01.R' : ('upperarm02.R_tl', 'lowerarm01.R_tl'),
  'lowerarm02.R' : ('lowerarm01.R_tl', 'lowerarm02.R_tl'),
  'wrist.R' : ('lowerarm02.R_tl', 'wrist.R_tl'),
  'finger1-1.R' : ('finger1-1.R_hd', 'finger1-1.R_tl'),
  'finger1-2.R' : ('finger1-1.R_tl', 'finger1-2.R_tl'),
  'finger1-3.R' : ('finger1-2.R_tl', 'finger1-3.R_tl'),
  'metacarpal4.R' : ('metacarpal4.R_hd', 'metacarpal4.R_tl'),
  'finger5-1.R' : ('metacarpal4.R_tl', 'finger5-1.R_tl'),
  'finger5-2.R' : ('finger5-1.R_tl', 'finger5-2.R_tl'),
  'finger5-3.R' : ('finger5-2.R_tl', 'finger5-3.R_tl'),
  'metacarpal1.R' : ('wrist.R_tl', 'metacarpal1.R_tl'),
  'finger2-1.R' : ('metacarpal1.R_tl', 'finger2-1.R_tl'),
  'finger2-2.R' : ('finger2-1.R_tl', 'finger2-2.R_tl'),
  'finger2-3.R' : ('finger2-2.R_tl', 'finger2-3.R_tl'),
  'metacarpal2.R' : ('wrist.R_tl', 'metacarpal2.R_tl'),
  'finger3-1.R' : ('metacarpal2.R_tl', 'finger3-1.R_tl'),
  'finger3-2.R' : ('finger3-1.R_tl', 'finger3-2.R_tl'),
  'finger3-3.R' : ('finger3-2.R_tl', 'finger3-3.R_tl'),
  'metacarpal3.R' : ('metacarpal3.R_hd', 'metacarpal3.R_tl'),
  'finger4-1.R' : ('metacarpal3.R_tl', 'finger4-1.R_tl'),
  'finger4-2.R' : ('finger4-1.R_tl', 'finger4-2.R_tl'),
  'finger4-3.R' : ('finger4-2.R_tl', 'finger4-3.R_tl'),
  'shoulder.R' : ('clavicle.R_tl', 'shoulder.R_tl'),
  'scapula.R' : ('scapula.R_hd', 'scapula.R_tl'),
  'neck' : ('spine1_tl', 'neck_tl'),
  'platysma06.R' : ('platysma06.R_hd', 'platysma06.R_tl'),
  'platysma06.L' : ('platysma06.L_hd', 'platysma06.L_tl'),
  'head' : ('neck_tl', 'head_tl'),
  'jaw' : ('jaw_hd', 'jaw_tl'),
  'tongue00' : ('jaw_tl', 'tongue00_tl'),
  'tongue01' : ('tongue00_tl', 'tongue01_tl'),
  'tongue02' : ('tongue01_tl', 'tongue02_tl'),
  'tongue03' : ('tongue02_tl', 'tongue03_tl'),
  'tongue04' : ('tongue03_tl', 'tongue04_tl'),
  'eye.R' : ('eye.R_hd', 'eye.R_tl'),
  'eye.L' : ('eye.L_hd', 'eye.L_tl'),
  'orbicularis04.R' : ('orbicularis04.R_hd', 'orbicularis04.R_tl'),
  'orbicularis04.L' : ('orbicularis04.L_hd', 'orbicularis04.L_tl'),
  'levator02.R' : ('levator02.R_hd', 'levator02.R_tl'),
  'levator03.R' : ('levator02.R_tl', 'levator03.R_tl'),
  'levator04.R' : ('levator03.R_tl', 'levator04.R_tl'),
  'levator05.R' : ('levator04.R_tl', 'levator05.R_tl'),
  'temporalis02.L' : ('temporalis02.L_hd', 'temporalis02.L_tl'),
  'temporalis03.L' : ('temporalis02.L_tl', 'temporalis03.L_tl'),
  'risorius02.L' : ('temporalis03.L_tl', 'risorius02.L_tl'),
  'risorius03.L' : ('risorius02.L_tl', 'risorius03.L_tl'),
  'levator02.L' : ('levator02.L_hd', 'levator02.L_tl'),
  'levator03.L' : ('levator02.L_tl', 'levator03.L_tl'),
  'levator04.L' : ('levator03.L_tl', 'levator04.L_tl'),
  'levator05.L' : ('levator04.L_tl', 'levator05.L_tl'),
  'special01' : ('special01_hd', 'special01_tl'),
  'oris04.R' : ('special01_tl', 'oris04.R_tl'),
  'oris03.R' : ('oris04.R_tl', 'oris03.R_tl'),
  'oris04.L' : ('special01_tl', 'oris04.L_tl'),
  'oris03.L' : ('oris04.L_tl', 'oris03.L_tl'),
  'oris05' : ('special01_tl', 'oris05_tl'),
  'special02' : ('special02_hd', 'special02_tl'),
  'oris06.L' : ('special02_tl', 'oris06.L_tl'),
  'oris07.L' : ('oris06.L_tl', 'oris07.L_tl'),
  'oris06.R' : ('special02_tl', 'oris06.R_tl'),
  'oris07.R' : ('oris06.R_tl', 'oris07.R_tl'),
  'oris02' : ('oris02_hd', 'oris02_tl'),
  'oris01' : ('oris02_tl', 'oris01_tl'),
  'temporalis01.L' : ('temporalis01.L_hd', 'temporalis01.L_tl'),
  'oculi02.L' : ('temporalis01.L_tl', 'oculi02.L_tl'),
  'oculi01.L' : ('oculi02.L_tl', 'oculi01.L_tl'),
  'oculi03.L' : ('oculi01.L_tl', 'oculi03.L_tl'),
  'temporalis01.R' : ('temporalis01.R_hd', 'temporalis01.R_tl'),
  'oculi02.R' : ('temporalis01.R_tl', 'oculi02.R_tl'),
  'oculi01.R' : ('oculi02.R_tl', 'oculi01.R_tl'),
  'oculi03.R' : ('oculi01.R_tl', 'oculi03.R_tl'),
  'temporalis02.R' : ('temporalis02.R_hd', 'temporalis02.R_tl'),
  'temporalis03.R' : ('temporalis02.R_tl', 'temporalis03.R_tl'),
  'risorius02.R' : ('temporalis03.R_tl', 'risorius02.R_tl'),
  'risorius03.R' : ('risorius02.R_tl', 'risorius03.R_tl'),
  'orbicularis03.R' : ('orbicularis03.R_hd', 'orbicularis03.R_tl'),
  'orbicularis03.L' : ('orbicularis03.L_hd', 'orbicularis03.L_tl'),
  'frontalis02.L' : ('frontalis02.L_hd', 'frontalis02.L_tl'),
  'frontalis01.L' : ('frontalis02.L_tl', 'frontalis01.L_tl'),
  'frontalis02.R' : ('frontalis02.R_hd', 'frontalis02.R_tl'),
  'frontalis01.R' : ('frontalis02.R_tl', 'frontalis01.R_tl'),
  'special03' : ('special03_hd', 'special03_tl'),
  'levator06.R' : ('levator06.R_hd', 'levator06.R_tl'),
  'levator06.L' : ('levator06.L_hd', 'levator06.L_tl'),
  'platysma03.R' : ('platysma03.R_hd', 'platysma03.R_tl'),
  'platysma03.L' : ('platysma03.L_hd', 'platysma03.L_tl'),

}

Armature = {
  'root' : (-0.000, None, 0, L_MAIN),

  'pelvis.R' : (1.000, 'root', F_DEF|F_CON, L_MAIN),
  'upperleg.R' : ("PlaneLeg.R", 'pelvis.R', F_DEF|F_CON, L_MAIN),
  'lowerleg01.R' : ("PlaneLeg.R", 'upperleg.R', F_DEF|F_CON, L_MAIN),
  'lowerleg02.R' : ("PlaneLeg.R", 'lowerleg01.R', F_DEF|F_CON, L_MAIN),
  'metatarsal1.R' : (-0.903, 'lowerleg02.R', F_DEF|F_CON, L_MAIN),
  'toe1-1.R' : (1.601, 'metatarsal1.R', F_DEF|F_CON, L_MAIN),
  'toe1-2.R' : (3.250, 'toe1-1.R', F_DEF|F_CON, L_MAIN),
  'metatarsal4.R' : (1.036, 'lowerleg02.R', F_DEF|F_CON, L_MAIN),
  'toe4-1.R' : (0.217, 'metatarsal4.R', F_DEF|F_CON, L_MAIN),
  'toe4-2.R' : (4.600, 'toe4-1.R', F_DEF|F_CON, L_MAIN),
  'toe4-3.R' : (1.802, 'toe4-2.R', F_DEF|F_CON, L_MAIN),
  'metatarsal3.R' : (0.505, 'lowerleg02.R', F_DEF|F_CON, L_MAIN),
  'toe3-1.R' : (6.798, 'metatarsal3.R', F_DEF|F_CON, L_MAIN),
  'toe3-2.R' : (5.190, 'toe3-1.R', F_DEF|F_CON, L_MAIN),
  'toe3-3.R' : (3.692, 'toe3-2.R', F_DEF|F_CON, L_MAIN),
  'metatarsal5.R' : (1.330, 'lowerleg02.R', F_DEF|F_CON, L_MAIN),
  'toe5-1.R' : (-0.198, 'metatarsal5.R', F_DEF|F_CON, L_MAIN),
  'toe5-2.R' : (3.944, 'toe5-1.R', F_DEF|F_CON, L_MAIN),
  'toe5-3.R' : (6.158, 'toe5-2.R', F_DEF|F_CON, L_MAIN),
  'heel.R' : (0.012, 'lowerleg02.R', F_DEF|F_CON, L_MAIN),
  'metatarsal2.R' : (-0.126, 'lowerleg02.R', F_DEF|F_CON, L_MAIN),
  'toe2-1.R' : (1.375, 'metatarsal2.R', F_DEF|F_CON, L_MAIN),
  'toe2-2.R' : (7.202, 'toe2-1.R', F_DEF|F_CON, L_MAIN),
  'toe2-3.R' : (4.623, 'toe2-2.R', F_DEF|F_CON, L_MAIN),

  'pelvis.L' : (-1.000, 'root', F_DEF|F_CON, L_MAIN),
  'upperleg.L' : ("PlaneLeg.L", 'pelvis.L', F_DEF|F_CON, L_MAIN),
  'lowerleg01.L' : ("PlaneLeg.L", 'upperleg.L', F_DEF|F_CON, L_MAIN),
  'lowerleg02.L' : ("PlaneLeg.L", 'lowerleg01.L', F_DEF|F_CON, L_MAIN),
  'metatarsal1.L' : (0.903, 'lowerleg02.L', F_DEF|F_CON, L_MAIN),
  'toe1-1.L' : (-1.601, 'metatarsal1.L', F_DEF|F_CON, L_MAIN),
  'toe1-2.L' : (-3.250, 'toe1-1.L', F_DEF|F_CON, L_MAIN),
  'metatarsal5.L' : (-1.330, 'lowerleg02.L', F_DEF|F_CON, L_MAIN),
  'toe5-1.L' : (0.198, 'metatarsal5.L', F_DEF|F_CON, L_MAIN),
  'toe5-2.L' : (-3.944, 'toe5-1.L', F_DEF|F_CON, L_MAIN),
  'toe5-3.L' : (-6.158, 'toe5-2.L', F_DEF|F_CON, L_MAIN),
  'metatarsal3.L' : (-0.505, 'lowerleg02.L', F_DEF|F_CON, L_MAIN),
  'toe3-1.L' : (-6.798, 'metatarsal3.L', F_DEF|F_CON, L_MAIN),
  'toe3-2.L' : (-5.190, 'toe3-1.L', F_DEF|F_CON, L_MAIN),
  'toe3-3.L' : (-3.692, 'toe3-2.L', F_DEF|F_CON, L_MAIN),
  'metatarsal2.L' : (0.126, 'lowerleg02.L', F_DEF|F_CON, L_MAIN),
  'toe2-1.L' : (-1.375, 'metatarsal2.L', F_DEF|F_CON, L_MAIN),
  'toe2-2.L' : (-7.202, 'toe2-1.L', F_DEF|F_CON, L_MAIN),
  'toe2-3.L' : (-4.623, 'toe2-2.L', F_DEF|F_CON, L_MAIN),
  'heel.L' : (-0.012, 'lowerleg02.L', F_DEF|F_CON, L_MAIN),
  'metatarsal4.L' : (-1.036, 'lowerleg02.L', F_DEF|F_CON, L_MAIN),
  'toe4-1.L' : (-0.217, 'metatarsal4.L', F_DEF|F_CON, L_MAIN),
  'toe4-2.L' : (-4.600, 'toe4-1.L', F_DEF|F_CON, L_MAIN),
  'toe4-3.L' : (-1.802, 'toe4-2.L', F_DEF|F_CON, L_MAIN),

  'spine5' : (0.000, 'root', F_DEF|F_CON, L_MAIN),
  'spine4' : (0.000, 'spine5', F_DEF, L_MAIN),
  'spine3' : (0.000, 'spine4', F_DEF, L_MAIN),
  'spine2' : (0.000, 'spine3', F_DEF, L_MAIN),
  'spine1' : (0.000, 'spine2', F_DEF, L_MAIN),

  'clavicle.L' : (0.035, 'spine1', F_DEF, L_MAIN),
  'shoulder.L' : (1.040, 'clavicle.L', F_DEF, L_MAIN|L_TWEAK),
  'scapula.L' : (0.101, 'clavicle.L', F_DEF, L_MAIN),
  'upperarm01.L' : ("PlaneArm.L", 'clavicle.L', F_DEF, L_MAIN),
  'upperarm02.L' : ("PlaneArm.L", 'upperarm01.L', F_DEF|F_CON, L_MAIN),
  'lowerarm01.L' : ("PlaneArm.L", 'upperarm02.L', F_DEF|F_CON, L_MAIN),
  'lowerarm02.L' : ("PlaneArm.L", 'lowerarm01.L', F_DEF|F_CON, L_MAIN),
  'wrist.L' : (-2.358, 'lowerarm02.L', F_DEF|F_CON, L_MAIN),
  'finger1-1.L' : ("PlaneThumb.L", 'wrist.L', F_DEF, L_MAIN),
  'finger1-2.L' : ("PlaneThumb.L", 'finger1-1.L', F_DEF|F_CON, L_MAIN),
  'finger1-3.L' : ("PlaneThumb.L", 'finger1-2.L', F_DEF|F_CON, L_MAIN),
  'metacarpal4.L' : ("PlanePinky.L", 'wrist.L', F_DEF, L_MAIN),
  'finger5-1.L' : ("PlanePinky.L", 'metacarpal4.L', F_DEF|F_CON, L_MAIN),
  'finger5-2.L' : ("PlanePinky.L", 'finger5-1.L', F_DEF|F_CON, L_MAIN),
  'finger5-3.L' : ("PlanePinky.L", 'finger5-2.L', F_DEF|F_CON, L_MAIN),
  'metacarpal1.L' : ("PlaneIndex.L", 'wrist.L', F_DEF|F_CON, L_MAIN),
  'finger2-1.L' : ("PlaneIndex.L", 'metacarpal1.L', F_DEF|F_CON, L_MAIN),
  'finger2-2.L' : ("PlaneIndex.L", 'finger2-1.L', F_DEF|F_CON, L_MAIN),
  'finger2-3.L' : ("PlaneIndex.L", 'finger2-2.L', F_DEF|F_CON, L_MAIN),
  'metacarpal2.L' : ("PlaneMiddle.L", 'wrist.L', F_DEF|F_CON, L_MAIN),
  'finger3-1.L' : ("PlaneMiddle.L", 'metacarpal2.L', F_DEF|F_CON, L_MAIN),
  'finger3-2.L' : ("PlaneMiddle.L", 'finger3-1.L', F_DEF|F_CON, L_MAIN),
  'finger3-3.L' : ("PlaneMiddle.L", 'finger3-2.L', F_DEF|F_CON, L_MAIN),
  'metacarpal3.L' : ("PlaneRing.L", 'wrist.L', F_DEF, L_MAIN),
  'finger4-1.L' : ("PlaneRing.L", 'metacarpal3.L', F_DEF|F_CON, L_MAIN),
  'finger4-2.L' : ("PlaneRing.L", 'finger4-1.L', F_DEF|F_CON, L_MAIN),
  'finger4-3.L' : ("PlaneRing.L", 'finger4-2.L', F_DEF|F_CON, L_MAIN),

  'clavicle.R' : (-0.035, 'spine1', F_DEF, L_MAIN),
  'shoulder.R' : (-1.040, 'clavicle.R', F_DEF|F_CON, L_MAIN|L_TWEAK),
  'scapula.R' : (-0.101, 'clavicle.R', F_DEF, L_MAIN),
  'upperarm01.R' : ("PlaneArm.R", 'clavicle.R', F_DEF, L_MAIN),
  'upperarm02.R' : ("PlaneArm.R", 'upperarm01.R', F_DEF|F_CON, L_MAIN),
  'lowerarm01.R' : ("PlaneArm.R", 'upperarm02.R', F_DEF|F_CON, L_MAIN),
  'lowerarm02.R' : ("PlaneArm.R", 'lowerarm01.R', F_DEF|F_CON, L_MAIN),
  'wrist.R' : (2.358, 'lowerarm02.R', F_DEF|F_CON, L_MAIN),
  'finger1-1.R' : ("PlaneThumb.R", 'wrist.R', F_DEF, L_MAIN),
  'finger1-2.R' : ("PlaneThumb.R", 'finger1-1.R', F_DEF|F_CON, L_MAIN),
  'finger1-3.R' : ("PlaneThumb.R", 'finger1-2.R', F_DEF|F_CON, L_MAIN),
  'metacarpal4.R' : ("PlanePinky.R", 'wrist.R', F_DEF, L_MAIN),
  'finger5-1.R' : ("PlanePinky.R", 'metacarpal4.R', F_DEF|F_CON, L_MAIN),
  'finger5-2.R' : ("PlanePinky.R", 'finger5-1.R', F_DEF|F_CON, L_MAIN),
  'finger5-3.R' : ("PlanePinky.R", 'finger5-2.R', F_DEF|F_CON, L_MAIN),
  'metacarpal1.R' : ("PlaneIndex.R", 'wrist.R', F_DEF|F_CON, L_MAIN),
  'finger2-1.R' : ("PlaneIndex.R", 'metacarpal1.R', F_DEF|F_CON, L_MAIN),
  'finger2-2.R' : ("PlaneIndex.R", 'finger2-1.R', F_DEF|F_CON, L_MAIN),
  'finger2-3.R' : ("PlaneIndex.R", 'finger2-2.R', F_DEF|F_CON, L_MAIN),
  'metacarpal2.R' : ("PlaneMiddle.R", 'wrist.R', F_DEF|F_CON, L_MAIN),
  'finger3-1.R' : ("PlaneMiddle.R", 'metacarpal2.R', F_DEF|F_CON, L_MAIN),
  'finger3-2.R' : ("PlaneMiddle.R", 'finger3-1.R', F_DEF|F_CON, L_MAIN),
  'finger3-3.R' : ("PlaneMiddle.R", 'finger3-2.R', F_DEF|F_CON, L_MAIN),
  'metacarpal3.R' : ("PlaneRing.R", 'wrist.R', F_DEF, L_MAIN),
  'finger4-1.R' : ("PlaneRing.R", 'metacarpal3.R', F_DEF|F_CON, L_MAIN),
  'finger4-2.R' : ("PlaneRing.R", 'finger4-1.R', F_DEF|F_CON, L_MAIN),
  'finger4-3.R' : ("PlaneRing.R", 'finger4-2.R', F_DEF|F_CON, L_MAIN),

  'neck' : (0.000, 'spine1', F_DEF|F_CON, L_MAIN),
  'head' : (0.000, 'neck', F_DEF|F_CON, L_MAIN),
  'jaw' : (0.000, 'head', F_DEF, L_FACE),

  'platysma06.R' : (0.225, 'neck', F_DEF, L_FACE),
  'platysma06.L' : (-0.225, 'neck', F_DEF, L_FACE),
  'platysma03.R' : (-0.316, 'neck', F_DEF, L_FACE),
  'platysma03.L' : (0.316, 'neck', F_DEF, L_FACE),

  'tongue00' : (0.000, 'jaw', F_DEF|F_CON, L_FACE),
  'tongue01' : (-0.0, 'tongue00', F_DEF, L_FACE),
  'tongue02' : (0.000, 'tongue01', F_DEF|F_CON, L_FACE),
  'tongue03' : (0.000, 'tongue02', F_DEF|F_CON, L_FACE),
  'tongue04' : (0.000, 'tongue03', F_DEF|F_CON, L_FACE),

  'eye.R' : ('PlaneEye.L', 'head', F_DEF, L_MAIN),
  'eye.L' : ('PlaneEye.R', 'head', F_DEF, L_MAIN),

  'orbicularis04.R' : (-1.397, 'head', F_DEF, L_FACE),
  'orbicularis04.L' : (1.397, 'head', F_DEF, L_FACE),
  'levator02.R' : (0.353, 'head', F_DEF, L_FACE),
  'levator03.R' : (0.306, 'levator02.R', F_DEF|F_CON, L_FACE),
  'levator04.R' : (0.621, 'levator03.R', F_DEF|F_CON, L_FACE),
  'levator05.R' : (0.167, 'levator04.R', F_DEF|F_CON, L_FACE),
  'temporalis02.L' : (-0.171, 'head', F_DEF, L_FACE),
  'temporalis03.L' : (-1.481, 'temporalis02.L', F_DEF|F_CON, L_FACE),
  'risorius02.L' : (-0.544, 'temporalis03.L', F_DEF|F_CON, L_FACE),
  'risorius03.L' : (0.042, 'risorius02.L', F_DEF|F_CON, L_FACE),
  'levator02.L' : (-0.353, 'head', F_DEF, L_FACE),
  'levator03.L' : (-0.306, 'levator02.L', F_DEF|F_CON, L_FACE),
  'levator04.L' : (-0.621, 'levator03.L', F_DEF|F_CON, L_FACE),
  'levator05.L' : (-0.167, 'levator04.L', F_DEF|F_CON, L_FACE),
  'special01' : (-6.280, 'head', F_DEF, L_FACE),
  'oris04.R' : (-0.047, 'special01', F_DEF, L_FACE),
  'oris03.R' : (0.377, 'oris04.R', F_DEF|F_CON, L_FACE),
  'oris04.L' : (0.047, 'special01', F_DEF, L_FACE),
  'oris03.L' : (-0.377, 'oris04.L', F_DEF|F_CON, L_FACE),
  'oris05' : (1.319, 'special01', F_DEF, L_FACE),
  'special02' : (-2.838, 'head', F_DEF, L_FACE),
  'oris06.L' : (-3.076, 'special02', F_DEF, L_FACE),
  'oris07.L' : (-2.518, 'oris06.L', F_DEF|F_CON, L_FACE),
  'oris06.R' : (3.076, 'special02', F_DEF, L_FACE),
  'oris07.R' : (2.518, 'oris06.R', F_DEF|F_CON, L_FACE),
  'oris02' : (2.983, 'oris06.R', F_DEF, L_FACE),
  'oris01' : (0.000, 'oris02', F_DEF|F_CON, L_FACE),
  'temporalis01.L' : (2.076, 'head', F_DEF, L_FACE),
  'oculi02.L' : (0.607, 'temporalis01.L', F_DEF|F_CON, L_FACE),
  'oculi01.L' : (0.350, 'oculi02.L', F_DEF|F_CON, L_FACE),
  'oculi03.L' : (-0.572, 'oculi01.L', F_DEF|F_CON, L_FACE),
  'temporalis01.R' : (-2.076, 'head', F_DEF, L_FACE),
  'oculi02.R' : (-0.607, 'temporalis01.R', F_DEF, L_FACE),
  'oculi01.R' : (-0.350, 'oculi02.R', F_DEF|F_CON, L_FACE),
  'oculi03.R' : (0.572, 'oculi01.R', F_DEF|F_CON, L_FACE),
  'temporalis02.R' : (0.171, 'head', F_DEF, L_FACE),
  'temporalis03.R' : (1.481, 'temporalis02.R', F_DEF|F_CON, L_FACE),
  'risorius02.R' : (0.544, 'temporalis03.R', F_DEF|F_CON, L_FACE),
  'risorius03.R' : (-0.042, 'risorius02.R', F_DEF|F_CON, L_FACE),
  'orbicularis03.R' : (-0.397, 'head', F_DEF, L_FACE),
  'orbicularis03.L' : (0.397, 'head', F_DEF, L_FACE),
  'frontalis02.L' : (1.469, 'head', F_DEF, L_FACE),
  'frontalis01.L' : (0.450, 'frontalis02.L', F_DEF|F_CON, L_FACE),
  'frontalis02.R' : (-1.469, 'head', F_DEF, L_FACE),
  'frontalis01.R' : (-0.450, 'frontalis02.R', F_DEF|F_CON, L_FACE),
  'special03' : (-0.049, 'head', F_DEF, L_FACE),
  'levator06.R' : (0.634, 'special03', F_DEF, L_FACE),
  'levator06.L' : (-0.634, 'special03', F_DEF, L_FACE),
}

Planes = {}
Constraints = {}
LocationLimits = {}
RotationLimits = {}
CustomShapes = {}
