#!/usr/bin/python3

# These are the subdirs that can contain third-part materials for
# core assets.

ALL_CORE_ASSET_DIRS_WITH_MATERIALS_AS_TEXT='''    
clothes/fedora01
clothes/female_casualsuit01
clothes/female_casualsuit02
clothes/female_elegantsuit01
clothes/female_sportsuit01
clothes/male_casualsuit01
clothes/male_casualsuit02
clothes/male_casualsuit03
clothes/male_casualsuit04
clothes/male_casualsuit05
clothes/male_casualsuit06
clothes/male_elegantsuit01
clothes/male_worksuit01
clothes/shoes01
clothes/shoes02
clothes/shoes03
clothes/shoes04
clothes/shoes05
clothes/shoes06
eyebrows/eyebrow001
eyebrows/eyebrow002
eyebrows/eyebrow003
eyebrows/eyebrow004
eyebrows/eyebrow005
eyebrows/eyebrow006
eyebrows/eyebrow007
eyebrows/eyebrow008
eyebrows/eyebrow009
eyebrows/eyebrow010
eyebrows/eyebrow011
eyebrows/eyebrow012
eyelashes/eyelashes01
eyelashes/eyelashes02
eyelashes/eyelashes03
eyelashes/eyelashes04
eyes/high-poly
eyes/low-poly
hair/afro01
hair/bob01
hair/bob02
hair/braid01
hair/long01
hair/ponytail01
hair/short01
hair/short02
hair/short03
hair/short04
teeth/teeth_base
teeth/teeth_shape01
teeth/teeth_shape02
teeth/teeth_shape03
teeth/teeth_shape04
teeth/teeth_shape05
tongue/tongue01
'''

