'''Autogenerated by xml_generate script, do not edit!'''
from OpenGL import platform as _p, arrays
# Code generation uses this
from OpenGL.raw.GL import _types as _cs
# End users want this...
from OpenGL.raw.GL._types import *
from OpenGL.raw.GL import _errors
from OpenGL.constant import Constant as _C

import ctypes
_EXTENSION_NAME = 'GL_NV_primitive_restart'
def _f( function ):
    return _p.createFunction( function,_p.PLATFORM.GL,'GL_NV_primitive_restart',error_checker=_errors._error_checker)
GL_PRIMITIVE_RESTART_INDEX_NV=_C('GL_PRIMITIVE_RESTART_INDEX_NV',0x8559)
GL_PRIMITIVE_RESTART_NV=_C('GL_PRIMITIVE_RESTART_NV',0x8558)
@_f
@_p.types(None,_cs.GLuint)
def glPrimitiveRestartIndexNV(index):pass
@_f
@_p.types(None,)
def glPrimitiveRestartNV():pass
